version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: knostic-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
      PORT: "3000"
      LOG_LEVEL: info
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: knostic-app
    depends_on:
      - server
    ports:
      - "5173:80"
    restart: unless-stopped
